---
abstract: 'a scope based object note and option store '
author:
  - 'Daichi Hiroki <hirokidaichi<AT>gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ScopeSession
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Error::Simple: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
